language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - go get -t -v ./...
  - go get github.com/go-playground/overalls

script:
  - overalls -project=github.com/plandem/xlsx -covermode=atomic -- -race -v
  - mv overalls.coverprofile coverage.txt
  - rm profile.coverprofile

after_success:
  - bash <(curl -s https://codecov.io/bash)
